### ISSUE TITLE
Is this getting an update to torrentz2.eu ?

### ISSUE THREAD

**Issue by marcelmah** [mancuniancol/script.pulsar.torrentz-mc#1]
Is this getting an update to torrentz2.eu ?

**Comment by marcelmah** [comment]
Never mind, just found this one: https://github.com/mancuniancol/script.magnetic.torrentz-mc

**Comment by mancuniancol** [comment]
I've replaced this provider for this:
https://github.com/mancuniancol/script.magnetic.torrentz-mc
